name: Crispin
repository: https://github.com/DelveFore/crispin

packages:
  - packages/**

command:
  version:
    updateGitTagRefs: true
    workspaceChangelog: true

scripts:
  format:
    run: fvm flutter pub global run melos exec flutter format lib

  analyze:
    run: |
      fvm flutter pub global run melos exec -c 5 -- \
        dart analyze . --fatal-infos

    description: |
      Run `dart analyze` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.


  test:
    run: fvm flutter pub global run melos exec --dir-exists="test" --fail-fast -- fvm flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.

  publish:
    run: fvm flutter pub global run melos exec fvm dart pub publish
