name: crispin
description: Crispin Logger for Dart and Flutter, that allows to use transports along with the logger.
version: 0.2.0
homepage: https://github.com/delvefore/crispin

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
