name: sentry_crispin_transport
description: A dart and flutter Sentry Transport for Crispin Logger with levels.
version: 1.0.0+1
homepage: https://docs.page/delvefore/crispin/transport-sentry

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crispin: ^1.1.0
  sentry: ^7.7.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
