name: logger_crispin_transport
description: Crispin Transport for Logger (https://pub.dev/packages/logger)
version: 1.0.0
homepage: https://pub.dev/packages/logger

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crispin: ^0.1.0
  logger: ^1.1.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
