name: logger_crispin_transport
description: Crispin Transport for Logger
version: 1.1.0
homepage: https://docs.page/delvefore/crispin/transport-logger

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crispin: ^1.0.0
  logger: ^1.1.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
